### 
POST http://127.0.0.1:5000/level
Content-Type: application/json

{
  "name": "Initial",
  "description": "Ejemplo 5"
}

###
GET http://127.0.0.1:5000/level

###
GET http://127.0.0.1:5000/level/1

###
DELETE http://127.0.0.1:5000/level/3

###
PATCH  http://127.0.0.1:5000/level/2
